# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e904829c58ccc81ca31522fc3aa61214d10575b93c79e5a01fd3a50f18b61cf514cc0b1e5e8ec031302f99782a6ef4389781a81acefdc8fe6761555c3877f36e

test:
  secret_key_base: 50efa4a487d081ab77748e976edda602f3b4bff178b3025010da55d2ddfbb5c1f343eea69f6d0101210bb5273169b1683bea4e4265f2479d2561390a169575f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
